Shurjopay Log file Generated
 '2024-12-17 14:45:23,819 : INFO :gs shurjopay_plugin.logger_config : authenticate  https://sandbox.shurjopayment.com/api/'
 '2024-12-17 14:45:23,819 : INFO :gs shurjopay_plugin.logger_config : authenticate  https://sandbox.shurjopayment.com/api/get_token'
 '2024-12-17 14:45:24,087 : ERROR :gs shurjopay_plugin.logger_config : authenticate  sp_code:1064, sp_message:Unauthorized'
 '2024-12-17 14:45:24,121 : ERROR :gs django.request : log_response  Internal Server Error: /api/pay/'
Traceback (most recent call last):
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\base\pay.py", line 45, in makePayment
    result = engine.make_payment(model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\shurjopay_plugin\shurjopay_plugin.py", line 152, in make_payment
    self.AUTH_TOKEN = self.authenticate()
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\shurjopay_plugin\shurjopay_plugin.py", line 108, in authenticate
    raise ShurjopayException(
shurjopay_plugin.utils.ShurjopayException: ('1064', 'Unauthorized')
 '2024-12-17 14:45:26,214 : INFO :gs shurjopay_plugin.logger_config : authenticate  https://sandbox.shurjopayment.com/api/'
 '2024-12-17 14:45:26,214 : INFO :gs shurjopay_plugin.logger_config : authenticate  https://sandbox.shurjopayment.com/api/get_token'
 '2024-12-17 14:45:26,410 : ERROR :gs shurjopay_plugin.logger_config : authenticate  sp_code:1064, sp_message:Unauthorized'
 '2024-12-17 14:45:26,431 : ERROR :gs django.request : log_response  Internal Server Error: /api/pay/'
Traceback (most recent call last):
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\base\pay.py", line 45, in makePayment
    result = engine.make_payment(model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\shurjopay_plugin\shurjopay_plugin.py", line 152, in make_payment
    self.AUTH_TOKEN = self.authenticate()
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aristo Computers\Desktop\office\adsyclub\venv\Lib\site-packages\shurjopay_plugin\shurjopay_plugin.py", line 108, in authenticate
    raise ShurjopayException(
shurjopay_plugin.utils.ShurjopayException: ('1064', 'Unauthorized')
 '2024-12-17 14:50:37,293 : INFO :gs django.utils.autoreload : trigger_reload  C:\Users\Aristo Computers\Desktop\office\adsyclub\base\pay.py changed, reloading.'
